export const projects = [
  {
    title: "Functions App",
    description: "All kind of Beginner functions, working with text and inputs",
    img: "/images/1.png",
    src: "/1.Functions_App/index.html",
  },
  {
    title: "Random Generators",
    description: "All kind of Random generators functions",
    img: "/images/2.png",
    src: "/2.Random_Generators/index.html",
  },
  {
    title: "Modal Popup",
    description: "Modal popup with exit button ",
    img: "/images/3.png",
    src: "/3.Modal_Popup/index.html",
  },
  {
    title: "Converter App",
    description:
      "Currency converter, weight converter and Temperature converter apps",
    img: "/images/4.png",
    src: "/4.ConverterApp/index.html",
  },
  {
    title: "Password Toggle",
    description: "Hidde password",
    img: "/images/5.png",
    src: "/5.PasswordToggle/index.html",
  },
  {
    title: "Vertical Tabs",
    description: "Multiple Tabs",
    img: "/images/6.png",
    src: "/6.Vertical_Tabs/index.html",
  },
  {
    title: "Tip Calculator",
    description: "Calculate the tip",
    img: "/images/7.png",
    src: "/7.Tip_Calculator/index.html",
  },
  {
    title: "Feedback UI",
    description: "Getting Feedback using Emojis ",
    img: "/images/8.png",
    src: "/8.FeedbackUI/index.html",
  },
  {
    title: "freeCodeCamp Exercises",
    description: "JavaScript Exercises from freeCodeCamp tutorial",
    img: "/images/9.png",
    src: "/9.freeCodeCamp_Exercises/index.html",
  },
  {
    title: "Mircha Exercises",
    description: "JavaScript Exercises from Mirch course",
    img: "/images/10.png",
    src: "/10.MirchaExercises/index.html",
  },
  {
    title: "Body Mass Index Calculator",
    description: "Body Mass Index (BMI)",
    img: "/images/12.png",
    src: "/12.BodyMassIndexCalculator/index.html",
  },
  {
    title: "Note App",
    description: "Note App using localstorage to save data",
    img: "/images/13.png",
    src: "/13.NoteApp",
  },
  {
    title: "Loan Calculator",
    description:
      "Basic calculations of common loan types such as mortgages, auto loans, student loans, or personal loans",
    img: "/images/14.png",
    src: "/14.Loan-Calculator",
  },
  {
    title: "Weather App",
    description: "provide a national and local weather forecast for cities, using https://openweathermap.org/api",
    img: "/images/15.png",
    src: "/15.Weather-App",
  },
  {
    title: "Image Search App",
    description: "Image Gallery using Unsplash API",
    img: "/images/16.png",
    src: "/16.ImageSearchApp",
  },
  {
    title: "Basic Calculator",
    description: "Basic arithmetic calculator",
    img: "/images/17.png",
    src: "/17.Basic-Calculator",
  },
  {
    title: "Stopwatch",
    description: "Using setInterval() functions",
    img: "/images/18.png",
    src: "/18.Stopwatch",
  },
  {
    title: "Rock Paper Scissors",
    description: "All kind of generators functions",
    img: "/images/19.png",
    src: "/19.Rock-paper-scissors",
  },
  {
    title: "Pomodoro Timer",
    description: "All kind of generators functions",
    img: "/images/20.png",
    src: "/20.Pomodoro-Timer",
  },
  {
    title: "Dice Roll Simulator",
    description: "All kind of generators functions",
    img: "/images/21.png",
    src: "/21.Dice-Roll-Simulator",
  },
  {
    title: "Recipe Book App",
    description: "All kind of generators functions",
    img: "/images/22.png",
    src: "/22.Recipe-Book-App",
  },
  {
    title: "Animated login UI",
    description: "All kind of generators functions",
    img: "/images/23.png",
    src: "/23.Animated_Login_UI",
  },
  {
    title: "DarkMode Toggle",
    description: "All kind of generators functions",
    img: "/images/24.png",
    src: "/24.DarkModeToggle",
  },
  {
    title: "Dictonary",
    description: "Dictonary using https://dictionaryapi.dev/",
    img: "/images/25.png",
    src: "/25.Dictionary",
  },
  {
    title: "Survey Form",
    description: "freeCodeCamp survey form exercise",
    img: "/images/26.png",
    src: "/26.Survey_form",
  },
  {
    title: "Age calculator",
    description: "Age Calculator",
    img: "/images/27.png",
    src: "/27.Age-Calculator",
  },
];
